/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/nutricionistas/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_registrarNutricionista"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nutricionistas/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NutricionistasController_findMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["NutricionistasController_updateMe"];
        trace?: never;
    };
    "/api/pacientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PacientesController_findAll"];
        put?: never;
        post: operations["PacientesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PacientesController_findOne"];
        put?: never;
        post?: never;
        delete: operations["PacientesController_remove"];
        options?: never;
        head?: never;
        patch: operations["PacientesController_update"];
        trace?: never;
    };
    "/api/pacientes/{id}/telegram/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PacientesController_gerarLinkTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/me/consentimento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PacientesController_aceitarConsentimento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/me/consentimento/revogar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PacientesController_revogarConsentimento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/prontuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProntuariosController_findAll"];
        put?: never;
        post: operations["ProntuariosController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/prontuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProntuariosController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ProntuariosController_remove"];
        options?: never;
        head?: never;
        patch: operations["ProntuariosController_update"];
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/planos-alimentares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlanosAlimentaresController_findAll"];
        put?: never;
        post: operations["PlanosAlimentaresController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/planos-alimentares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlanosAlimentaresController_findOne"];
        put?: never;
        post?: never;
        delete: operations["PlanosAlimentaresController_remove"];
        options?: never;
        head?: never;
        patch: operations["PlanosAlimentaresController_update"];
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/planos-alimentares/{id}/aprovar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlanosAlimentaresController_aprovar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/planos-alimentares/{id}/calculo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlanosAlimentaresController_calcular"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/planos-alimentares/rascunho-ia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlanosAlimentaresController_gerarRascunhoIA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/planos-alimentares/{id}/duplicar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlanosAlimentaresController_duplicar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/planos-alimentares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeusPlanosAlimentaresController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/planos-alimentares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeusPlanosAlimentaresController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/planos-alimentares/{id}/calculo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeusPlanosAlimentaresController_calcular"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planos-alimentares/pendentes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FilaAprovacaoController_pendentes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assinaturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AssinaturasController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assinaturas/converter-para-pago": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AssinaturasController_converterParaPago"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assinaturas/trial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AssinaturasController_iniciarTrial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assinaturas/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssinaturasController_findMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assinaturas/me/faturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssinaturasController_listarFaturas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assinaturas/webhook/asaas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AssinaturasController_webhookAsaas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlimentosController_buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alimentos/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AlimentosController_buscarPorCodigo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/peso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistrosController_listarPeso"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/diario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistrosController_listarDiario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/peso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeusRegistrosController_listarPeso"];
        put?: never;
        post: operations["MeusRegistrosController_registrarPeso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/diario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeusRegistrosController_listarDiario"];
        put?: never;
        post: operations["MeusRegistrosController_registrarDiario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/anamnese": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnamneseController_buscarMaisRecente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{pacienteId}/anamnese/{id}/incorporar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AnamneseController_incorporar"];
        trace?: never;
    };
    "/api/me/anamnese": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MinhaAnamneseController_minhaAnamnese"];
        put?: never;
        post: operations["MinhaAnamneseController_enviar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterNutricionistaDto: {
            nome: string;
            email: string;
            senha: string;
            crn: string;
            telefone?: string;
            /** @enum {string} */
            plano?: "STARTER" | "PRO" | "CLINICA";
        };
        LoginDto: {
            email: string;
            senha: string;
            /** @enum {string} */
            role: "NUTRICIONISTA" | "PACIENTE";
        };
        NutricionistaMeDto: {
            id: string;
            nome: string;
            email: string;
            crn: string;
            telefone: string | null;
            cpfCnpj: string | null;
            ativo: boolean;
            /** Format: date-time */
            criadoEm: string;
        };
        UpdateNutricionistaDto: {
            nome?: string;
            telefone?: string;
            cpfCnpj?: string;
        };
        CreatePacienteDto: {
            nome: string;
            email: string;
            senha: string;
            telefone?: string;
            dataNascimento?: string;
            /** @enum {string} */
            sexoBiologico?: "MASCULINO" | "FEMININO";
        };
        UpdatePacienteDto: Record<string, never>;
        AceitarConsentimentoDto: {
            versaoTermo: string;
        };
        CreateProntuarioDto: {
            queixaPrincipal?: string;
            historicoClinico?: string;
            historicoFamiliar?: string;
            habitosAlimentares?: string;
            usoMedicamentos?: string;
            alergias?: string;
            intolerancias?: string;
            nivelAtividadeFisica?: string;
            observacoesGerais?: string;
            pesoKg?: number;
            alturaCm?: number;
            circunferenciaCintura?: number;
            circunferenciaQuadril?: number;
            percentualGordura?: number;
            imc?: number;
        };
        ProntuarioDto: {
            id: string;
            pacienteId: string;
            queixaPrincipal: string | null;
            historicoClinico: string | null;
            historicoFamiliar: string | null;
            habitosAlimentares: string | null;
            usoMedicamentos: string | null;
            alergias: string | null;
            intolerancias: string | null;
            nivelAtividadeFisica: string | null;
            observacoesGerais: string | null;
            /** @description Decimal serializado como string, ex.: "90.00". */
            pesoKg: string | null;
            alturaCm: string | null;
            circunferenciaCintura: string | null;
            circunferenciaQuadril: string | null;
            percentualGordura: string | null;
            imc: string | null;
            /** Format: date-time */
            criadoEm: string;
            /** Format: date-time */
            atualizadoEm: string;
        };
        UpdateProntuarioDto: Record<string, never>;
        CreatePlanoAlimentarDto: {
            titulo: string;
            objetivo?: string;
            caloriasAlvo?: number;
            refeicoes: Record<string, never>[];
            observacoes?: string;
            /** @enum {string} */
            origem?: "MANUAL" | "IA_RASCUNHO";
        };
        PlanoAlimentarDto: {
            id: string;
            pacienteId: string;
            titulo: string;
            objetivo: string | null;
            caloriasAlvo: number | null;
            /** @description JSON livre: [{ nome, horario, itens: [{ descricao?, alimentoCodigo?, quantidadeGramas? }] }]. */
            refeicoes: {
                [key: string]: unknown;
            }[];
            observacoes: string | null;
            /** @enum {string} */
            origem: "MANUAL" | "IA_RASCUNHO";
            /** @description Gate de compliance. Nas rotas /me/* nunca vem false. */
            aprovadoPeloNutri: boolean;
            ativo: boolean;
            /** Format: date-time */
            criadoEm: string;
            /** Format: date-time */
            atualizadoEm: string;
        };
        UpdatePlanoAlimentarDto: Record<string, never>;
        FonteTacoDto: {
            /** @example TACO */
            tabela: string;
            codigo: number;
            descricao: string;
        };
        ItemCalculadoDto: {
            descricao?: string;
            alimentoCodigo?: number;
            quantidadeGramas?: number;
            fonte: components["schemas"]["FonteTacoDto"] | null;
            kcal?: number;
            proteinaG?: number;
            lipideosG?: number;
            carboidratoG?: number;
            fibraG?: number;
        };
        MacrosDto: {
            kcal: number;
            proteinaG: number;
            lipideosG: number;
            carboidratoG: number;
            fibraG: number;
        };
        RefeicaoCalculadaDto: {
            nome?: string;
            horario?: string;
            itens: components["schemas"]["ItemCalculadoDto"][];
            total: components["schemas"]["MacrosDto"];
        };
        CalculoNutricionalDto: {
            porRefeicao: components["schemas"]["RefeicaoCalculadaDto"][];
            total: components["schemas"]["MacrosDto"];
            itensSemFonte: components["schemas"]["ItemCalculadoDto"][];
        };
        GerarRascunhoIaDto: {
            perguntaNutricionista: string;
        };
        FonteRagDto: {
            source: string;
            trecho: string;
            similaridade: number;
        };
        RascunhoIaDto: {
            rascunho: string;
            fontesUtilizadas: components["schemas"]["FonteRagDto"][];
            modeloUtilizado: string;
            /** @description Disclaimer CFN — "sugestão para revisão do profissional". */
            disclaimer: string;
        };
        DuplicarPlanoAlimentarDto: {
            pacienteDestinoId: string;
        };
        PlanoPendenteDto: {
            id: string;
            pacienteId: string;
            pacienteNome: string;
            titulo: string;
            /** @enum {string} */
            origem: "MANUAL" | "IA_RASCUNHO";
            /** Format: date-time */
            criadoEm: string;
        };
        CreateAssinaturaDto: {
            /** @enum {string} */
            plano: "STARTER" | "PRO" | "CLINICA";
            trialAte?: string;
        };
        AssinaturaDto: {
            id: string;
            nutricionistaId: string;
            /** @enum {string} */
            plano: "STARTER" | "PRO" | "CLINICA";
            /** @enum {string} */
            status: "TRIAL" | "ATIVA" | "INADIMPLENTE" | "CANCELADA" | "EXPIRADA";
            /** Format: date-time */
            trialAte: string | null;
            /** Format: date-time */
            inadimplenteDesde: string | null;
            asaasCustomerId: string | null;
            asaasSubscriptionId: string | null;
            /** Format: date-time */
            criadoEm: string;
            /** Format: date-time */
            atualizadoEm: string;
        };
        ConverterParaPagoDto: {
            /** @enum {string} */
            plano: "STARTER" | "PRO" | "CLINICA";
        };
        FaturaDto: {
            id: string;
            valor: number;
            /** @enum {string} */
            status: "paga" | "pendente" | "falhou" | "outro";
            /** @description Data de vencimento (YYYY-MM-DD). */
            vencimento: string;
            /** @description Data de pagamento (YYYY-MM-DD). */
            pagoEm: string | null;
            /** @description Página do recibo/fatura hospedada pela Asaas. */
            reciboUrl: string | null;
            /** @description Página do boleto hospedada pela Asaas. */
            boletoUrl: string | null;
        };
        AsaasWebhookPaymentDto: {
            subscription?: string;
            status?: string;
        };
        AsaasWebhookDto: {
            event: string;
            payment?: components["schemas"]["AsaasWebhookPaymentDto"];
        };
        AlimentoTacoDto: {
            codigo: number;
            categoria: string;
            descricao: string;
            umidadePercent: number | null;
            kcal: number | null;
            kj: number | null;
            proteinaG: number | null;
            lipideosG: number | null;
            colesterolMg: number | null;
            carboidratoG: number | null;
            fibraG: number | null;
            cinzasG: number | null;
            calcioMg: number | null;
            magnesioMg: number | null;
            manganesMg: number | null;
            fosforoMg: number | null;
            ferroMg: number | null;
            sodioMg: number | null;
            potassioMg: number | null;
            cobreMg: number | null;
            zincoMg: number | null;
            retinolMcg: number | null;
            reMcg: number | null;
            raeMcg: number | null;
            tiaminaMg: number | null;
            riboflavinaMg: number | null;
            piridoxinaMg: number | null;
            niacinaMg: number | null;
            vitaminaCMg: number | null;
        };
        RegistroPesoDto: {
            id: string;
            pacienteId: string;
            pesoKg: string | number;
            /** Format: date-time */
            registradoEm: string;
        };
        RegistroDiarioDto: {
            id: string;
            pacienteId: string;
            texto: string | null;
            fotoUrl: string | null;
            /** Format: date-time */
            registradoEm: string;
        };
        CreateRegistroPesoDto: {
            pesoKg: number;
        };
        CreateRegistroDiarioDto: {
            texto?: string;
            fotoUrl?: string;
        };
        AnamneseAutodeclaradaDto: {
            id: string;
            pacienteId: string;
            /** @enum {string} */
            status: "PENDENTE_REVISAO" | "INCORPORADA";
            /** Format: date-time */
            respondidoEm: string;
            /** Format: date-time */
            incorporadoEm: string | null;
            incorporadoPorNutriId: string | null;
            objetivo: string | null;
            queixaPrincipal: string | null;
            historicoClinico: string | null;
            historicoFamiliar: string | null;
            habitosAlimentares: string | null;
            usoMedicamentos: string | null;
            alergias: string | null;
            intolerancias: string | null;
            nivelAtividadeFisica: string | null;
            preferenciasAversoes: string | null;
            rotinaRefeicoes: string | null;
            consumoAgua: string | null;
            habitoIntestinal: string | null;
            sono: string | null;
            consumoAlcool: string | null;
            tabagismo: string | null;
            gestacaoLactacao: string | null;
            praticaExercicio: string | null;
            suplementos: string | null;
            observacoesGerais: string | null;
            /** @description Decimal serializado como string, ex.: "72.50". */
            pesoDeclaradoKg: string | null;
            alturaDeclaradaCm: string | null;
        };
        CreateAnamneseAutodeclaradaDto: {
            objetivo?: string;
            queixaPrincipal?: string;
            historicoClinico?: string;
            historicoFamiliar?: string;
            habitosAlimentares?: string;
            usoMedicamentos?: string;
            alergias?: string;
            intolerancias?: string;
            nivelAtividadeFisica?: string;
            preferenciasAversoes?: string;
            rotinaRefeicoes?: string;
            consumoAgua?: string;
            habitoIntestinal?: string;
            sono?: string;
            consumoAlcool?: string;
            tabagismo?: string;
            gestacaoLactacao?: string;
            praticaExercicio?: string;
            suplementos?: string;
            observacoesGerais?: string;
            /** @description Peso auto-declarado (kg). Provisório, não oficial. */
            pesoDeclaradoKg?: number;
            /** @description Altura auto-declarada (cm). Provisória, não oficial. */
            alturaDeclaradaCm?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_registrarNutricionista: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterNutricionistaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NutricionistasController_findMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutricionistaMeDto"];
                };
            };
        };
    };
    NutricionistasController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNutricionistaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutricionistaMeDto"];
                };
            };
        };
    };
    PacientesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PacientesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePacienteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PacientesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PacientesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PacientesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePacienteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PacientesController_gerarLinkTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PacientesController_aceitarConsentimento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AceitarConsentimentoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PacientesController_revogarConsentimento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProntuariosController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProntuarioDto"][];
                };
            };
        };
    };
    ProntuariosController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProntuarioDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProntuarioDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProntuariosController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProntuarioDto"];
                };
            };
        };
    };
    ProntuariosController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProntuariosController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProntuarioDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProntuarioDto"];
                };
            };
        };
    };
    PlanosAlimentaresController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoAlimentarDto"][];
                };
            };
        };
    };
    PlanosAlimentaresController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanoAlimentarDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoAlimentarDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlanosAlimentaresController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoAlimentarDto"];
                };
            };
        };
    };
    PlanosAlimentaresController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlanosAlimentaresController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanoAlimentarDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoAlimentarDto"];
                };
            };
        };
    };
    PlanosAlimentaresController_aprovar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoAlimentarDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlanosAlimentaresController_calcular: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculoNutricionalDto"];
                };
            };
        };
    };
    PlanosAlimentaresController_gerarRascunhoIA: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GerarRascunhoIaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RascunhoIaDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    PlanosAlimentaresController_duplicar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicarPlanoAlimentarDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoAlimentarDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeusPlanosAlimentaresController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoAlimentarDto"][];
                };
            };
        };
    };
    MeusPlanosAlimentaresController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoAlimentarDto"];
                };
            };
        };
    };
    MeusPlanosAlimentaresController_calcular: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculoNutricionalDto"];
                };
            };
        };
    };
    FilaAprovacaoController_pendentes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanoPendenteDto"][];
                };
            };
        };
    };
    AssinaturasController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssinaturaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssinaturaDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssinaturaDto"];
                };
            };
        };
    };
    AssinaturasController_converterParaPago: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConverterParaPagoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssinaturaDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssinaturaDto"];
                };
            };
        };
    };
    AssinaturasController_iniciarTrial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssinaturaDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssinaturaDto"];
                };
            };
        };
    };
    AssinaturasController_findMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssinaturaDto"];
                };
            };
        };
    };
    AssinaturasController_listarFaturas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaturaDto"][];
                };
            };
        };
    };
    AssinaturasController_webhookAsaas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsaasWebhookDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlimentosController_buscar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlimentoTacoDto"][];
                };
            };
        };
    };
    AlimentosController_buscarPorCodigo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlimentoTacoDto"];
                };
            };
        };
    };
    RegistrosController_listarPeso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroPesoDto"][];
                };
            };
        };
    };
    RegistrosController_listarDiario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroDiarioDto"][];
                };
            };
        };
    };
    MeusRegistrosController_listarPeso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroPesoDto"][];
                };
            };
        };
    };
    MeusRegistrosController_registrarPeso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRegistroPesoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroPesoDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeusRegistrosController_listarDiario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroDiarioDto"][];
                };
            };
        };
    };
    MeusRegistrosController_registrarDiario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRegistroDiarioDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroDiarioDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnamneseController_buscarMaisRecente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnamneseAutodeclaradaDto"];
                };
            };
        };
    };
    AnamneseController_incorporar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pacienteId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnamneseAutodeclaradaDto"];
                };
            };
        };
    };
    MinhaAnamneseController_minhaAnamnese: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnamneseAutodeclaradaDto"];
                };
            };
        };
    };
    MinhaAnamneseController_enviar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnamneseAutodeclaradaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnamneseAutodeclaradaDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
